### ISSUE TITLE
Error when user Id is an integer

### ISSUE THREAD

**Issue by GiulioGenova** [pvgenuchten/pyGeoDataCrawler#13]
In some cases it can be that the user name (string) is not known and a user id number is returned by the function https://github.com/pvgenuchten/pyGeoDataCrawler/blob/cf25b9a2c281f8e36df43dd2a40ad7e797c96d92/geodatacrawler/utils.py#L478

Here the error
![image](https://github.com/pvgenuchten/pyGeoDataCrawler/assets/39799547/00a9a062-a79a-464d-831d-74e4e85cc338)

I will have a look at this

**Comment by GiulioGenova** [comment]
Hi @pvgenuchten I pushed a change that should fix the problem.

**Comment by pvgenuchten** [comment]
Thanx giulio
