### ISSUE TITLE
import 4000 .xml documents extracted from Zenodo, in Dublin Core schema

### ISSUE THREAD

**Issue by pvgenuchten** [pvgenuchten/pyGeoDataCrawler#25]

**Comment by hugodegrootwurnl** [comment]
Hoi Paul, Hier een paar .XMLs
[zenodo_xml.zip](https://github.com/pvgenuchten/pyGeoDataCrawler/files/14472695/zenodo_xml.zip)
Ik heb er in totaal 4196; Hier zijn ze allemaal:
[zenodo_xml_all4196.zip](https://github.com/pvgenuchten/pyGeoDataCrawler/files/14472697/zenodo_xml_all4196.zip)
